### ISSUE TITLE
Typo in config.php file

### ISSUE THREAD

**Issue by bassmanpaul** [joolanders/ytp-form-actions#1]
Hey team.

This file's icon path is slightly incorrect (https://github.com/joolanders/ytp-form-actions/blob/main/src/MyAction/config.json):

`"icon": "${url:~theme/modules/mymodule/src/MyAction/icon.svg}",`

Should be:

`"icon": "${url:~theme/modules/mymodules/src/MyAction/icon.svg}",`

(Was missing an `s`).

Thanks!

**Comment by miljan-aleksic** [comment]
Hi there,

seems you chosen to name your module as `mymodules` while our Getting Started guide indicates `mymodule` which match the current icon path. Or am I missing something?

But you can name the module however you want! Actually you SHOULD rename it to something more meaningful.

**Comment by bassmanpaul** [comment]
Hey,

Point 3 of your README says `mymodule`, so that took some debugging to work out why the demo didn't work.

I will be renaming it (just thought I'd mention it in case other people get confused in the future), as I'd like to build a form action that you guys can incorporate back into the Zoolanders package if you find it useful.

Line: `3. Place the contents of this repository into yootheme_mytheme/modules/mymodule;`

**Comment by bassmanpaul** [comment]
Hey,

My apologies, I just spotted my error!

I will be renaming it, as I'd like to build a form action that you guys can incorporate back into the Zoolanders package if you find it useful.

Thanks

**Comment by miljan-aleksic** [comment]
Hi!

to include something in the package will have to pass many tests, but we are always curious about what users build so feel free to drop us an email about it when is ready.

**Comment by bassmanpaul** [comment]
Sure, will do. It will be the ability to save a form submission to the database, so users have an on-site record of all form submissions.

**Comment by miljan-aleksic** [comment]
You might wanna wait for that one as it's in the works already :)

**Comment by bassmanpaul** [comment]
That's amazing! Do you have an estimate of when that feature will be released?

**Comment by miljan-aleksic** [comment]
Difficult to say as it's going to be part of a major update, maybe three to for weeks for the first private beta. If you want can add you as a beta tester for it and let you know when is ready to test.

**Comment by bassmanpaul** [comment]
Okay, good to know, thanks! Yeah I can be a beta tester for you guys.

**Comment by miljan-aleksic** [comment]
The saveToDatabase action is out now as part of the 1.8 release :)

**Comment by bassmanpaul** [comment]
Thanks Miljan, great job! I've been playing around with the new features and the database save is working really well. I also have a page which loads the database results into a table so admins can see the submissions.
